// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OcStockAPI.DataContext;

#nullable disable

namespace OcStockAPI.Migrations
{
    [DbContext(typeof(OcStockDbContext))]
    [Migration("20251007170825_MakeDateAddedNullable")]
    partial class MakeDateAddedNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventStock", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<int>("StockId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_id");

                    b.HasKey("EventId", "StockId");

                    b.HasIndex("StockId");

                    b.ToTable("Event_Stocks");
                });

            modelBuilder.Entity("OcStockAPI.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<decimal?>("CPI")
                        .HasColumnType("numeric")
                        .HasColumnName("cpi");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("Datetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime");

                    b.Property<decimal?>("FederalInterestRate")
                        .HasColumnType("numeric")
                        .HasColumnName("federal_interest_rate");

                    b.Property<decimal?>("Inflation")
                        .HasColumnType("numeric")
                        .HasColumnName("inflation");

                    b.Property<decimal?>("UnemploymentRate")
                        .HasColumnType("numeric")
                        .HasColumnName("unemployment_rate");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("OcStockAPI.Entities.EventMutualFund", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("MutualFundId")
                        .HasColumnType("integer");

                    b.HasKey("EventId", "MutualFundId");

                    b.HasIndex("MutualFundId");

                    b.ToTable("Event_MutualFunds");
                });

            modelBuilder.Entity("OcStockAPI.Entities.InvestorAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("account_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("AccountId");

                    b.ToTable("InvestorAccount");
                });

            modelBuilder.Entity("OcStockAPI.Entities.MarketNews", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("news_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NewsId"));

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("headline");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<int>("StockId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_id");

                    b.HasKey("NewsId");

                    b.HasIndex("StockId");

                    b.ToTable("MarketNews");
                });

            modelBuilder.Entity("OcStockAPI.Entities.MutualFund", b =>
                {
                    b.Property<int>("MutualFundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MutualFundId"));

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MutualFundId");

                    b.ToTable("MutualFunds");
                });

            modelBuilder.Entity("OcStockAPI.Entities.Portfolio", b =>
                {
                    b.Property<int>("PortfolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PortfolioId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PortfolioId");

                    b.HasIndex("AccountId");

                    b.ToTable("Portfolio");
                });

            modelBuilder.Entity("OcStockAPI.Entities.PortfolioMutualFund", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<int>("MutualFundId")
                        .HasColumnType("integer");

                    b.HasKey("PortfolioId", "MutualFundId");

                    b.HasIndex("MutualFundId");

                    b.ToTable("Portfolio_MutualFunds");
                });

            modelBuilder.Entity("OcStockAPI.Entities.PortfolioStock", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.HasKey("PortfolioId", "StockId");

                    b.HasIndex("StockId");

                    b.ToTable("Portfolio_Stocks");
                });

            modelBuilder.Entity("OcStockAPI.Entities.Settings.ApiCallLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CallDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CallType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("ApiCallLog");
                });

            modelBuilder.Entity("OcStockAPI.Entities.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("stock_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockId"));

                    b.Property<decimal>("ClosingValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("OpenValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<int>("TrackedStockId")
                        .HasColumnType("integer")
                        .HasColumnName("tracked_stock_id");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("StockId");

                    b.HasIndex("TrackedStockId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("OcStockAPI.Entities.StockHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<decimal?>("ClosedValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OpenedValue")
                        .HasColumnType("numeric");

                    b.Property<int>("StockId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_id");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("HistoryId");

                    b.HasIndex("StockId");

                    b.ToTable("StockHistory");
                });

            modelBuilder.Entity("OcStockAPI.Entities.TrackedStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_added");

                    b.Property<string>("StockName")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TrackedStocks");
                });

            modelBuilder.Entity("EventStock", b =>
                {
                    b.HasOne("OcStockAPI.Entities.Event", "Event")
                        .WithMany("EventStocks")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OcStockAPI.Entities.Stock", "Stock")
                        .WithMany("EventStocks")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("OcStockAPI.Entities.EventMutualFund", b =>
                {
                    b.HasOne("OcStockAPI.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OcStockAPI.Entities.MutualFund", "MutualFund")
                        .WithMany("EventMutualFunds")
                        .HasForeignKey("MutualFundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("MutualFund");
                });

            modelBuilder.Entity("OcStockAPI.Entities.MarketNews", b =>
                {
                    b.HasOne("OcStockAPI.Entities.Stock", "Stock")
                        .WithMany("MarketNews")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("OcStockAPI.Entities.Portfolio", b =>
                {
                    b.HasOne("OcStockAPI.Entities.InvestorAccount", "InvestorAccount")
                        .WithMany("Portfolios")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestorAccount");
                });

            modelBuilder.Entity("OcStockAPI.Entities.PortfolioMutualFund", b =>
                {
                    b.HasOne("OcStockAPI.Entities.MutualFund", "MutualFund")
                        .WithMany("PortfolioMutualFunds")
                        .HasForeignKey("MutualFundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OcStockAPI.Entities.Portfolio", "Portfolio")
                        .WithMany("PortfolioMutualFunds")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MutualFund");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("OcStockAPI.Entities.PortfolioStock", b =>
                {
                    b.HasOne("OcStockAPI.Entities.Portfolio", "Portfolio")
                        .WithMany("PortfolioStocks")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OcStockAPI.Entities.Stock", "Stock")
                        .WithMany("PortfolioStocks")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("OcStockAPI.Entities.Stock", b =>
                {
                    b.HasOne("OcStockAPI.Entities.TrackedStock", "TrackedStock")
                        .WithMany("Stocks")
                        .HasForeignKey("TrackedStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedStock");
                });

            modelBuilder.Entity("OcStockAPI.Entities.StockHistory", b =>
                {
                    b.HasOne("OcStockAPI.Entities.Stock", "Stock")
                        .WithMany("StockHistories")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("OcStockAPI.Entities.Event", b =>
                {
                    b.Navigation("EventStocks");
                });

            modelBuilder.Entity("OcStockAPI.Entities.InvestorAccount", b =>
                {
                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("OcStockAPI.Entities.MutualFund", b =>
                {
                    b.Navigation("EventMutualFunds");

                    b.Navigation("PortfolioMutualFunds");
                });

            modelBuilder.Entity("OcStockAPI.Entities.Portfolio", b =>
                {
                    b.Navigation("PortfolioMutualFunds");

                    b.Navigation("PortfolioStocks");
                });

            modelBuilder.Entity("OcStockAPI.Entities.Stock", b =>
                {
                    b.Navigation("EventStocks");

                    b.Navigation("MarketNews");

                    b.Navigation("PortfolioStocks");

                    b.Navigation("StockHistories");
                });

            modelBuilder.Entity("OcStockAPI.Entities.TrackedStock", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
