name: DatabaseProject Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-push-deploy:
    runs-on: "self-hosted"
    steps:
    -
      name: checkout
      uses: actions/checkout@v3   
    -
      name: get tag name
      run: echo "TAG_ENV=$(date +'%Y-%m-%dT%H%M%S')" >> "$GITHUB_ENV"
    -
      name: build
      run:  docker build -f ./Dockerfile -t databaseprojectapi:${{env.TAG_ENV}} .
    - 
      name: tag
      run: |  
         docker tag databaseprojectapi:${{env.TAG_ENV}} reg.dqcsapp.com/databaseprojectapi:${{env.TAG_ENV}}
         docker tag databaseprojectapi:${{env.TAG_ENV}} reg.dqcsapp.com/databaseprojectapi:latest
    - 
      name: push
      run: |  
         docker push reg.dqcsapp.com/databaseprojectapi:${{env.TAG_ENV}}
         docker push reg.dqcsapp.com/databaseprojectapi:latest
    -
      name: deploy kubernetes set image
      run: | 
         kubectl set image deployments/databaseprojectapi databaseprojectapi=reg.dqcsapp.com/databaseprojectapi:${{env.TAG_ENV}} --kubeconfig=/etc/kube/config
    -
      name: remove local images
      run : docker rmi -f $(docker images -aq)
